apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backtest

labels:
  - pairs:
      app.kubernetes.io/part-of: backtest
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap-live.yaml
  - configmap-backtest.yaml
  - pvc-backtest-results.yaml
  - pvc-backtest-cache.yaml
  - rbac-api-argo.yaml
  - job-migrate.yaml
  - deployment-api.yaml
  - service-api.yaml
  - deployment-controller.yaml
  - service-worker.yaml
  - statefulset-workers.yaml
  - cronjob-reconciler.yaml
  - cronjob-backtest-reconciler.yaml
  - workflowtemplate-backtest.yaml
  - deployment-web.yaml
  - service-web.yaml

images:
  - name: backtest-app
    newName: backtest-app
    newTag: latest
  - name: backtest-web
    newName: backtest-web
    newTag: latest
