apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backtest-results
  labels:
    app.kubernetes.io/name: backtest-results
    app.kubernetes.io/component: backtest
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
