apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/component: live-runtime
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: worker
  ports:
    - name: worker
      port: 8080
      targetPort: 8080
