apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../workflows

patches:
  - target:
      kind: PersistentVolumeClaim
      name: backtest-results
    patch: |-
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteOnce
  - target:
      kind: PersistentVolumeClaim
      name: backtest-cache
    patch: |-
      - op: replace
        path: /spec/accessModes
        value:
          - ReadWriteOnce
