apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backtest-workflows

labels:
  - pairs:
      app.kubernetes.io/part-of: backtest
    includeSelectors: false

resources:
  - namespace.yaml
  - rbac-backtest-workflow.yaml
  - rbac-api-workflow-submitter.yaml
  - pvc-backtest-results.yaml
  - pvc-backtest-cache.yaml
  - service-postgres-external.yaml
