apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backtest

resources:
  - ../../base
  - postgres.yaml
  - service-postgres.yaml
  - redis.yaml
  - service-redis.yaml
  - ingress-class-traefik.yaml
  - ingress-web.yaml

secretGenerator:
  - name: app-secrets
    literals:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@postgres:5432/backtest

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patch-migrate-wait.yaml
  - path: patch-api-init.yaml
  - path: patch-web-replicas.yaml
  - path: patch-pvc-hostpath.yaml
