apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backtest-results
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backtest-cache
spec:
  accessModes:
    - ReadWriteOnce
